name: Create Discussion

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set Date
        run: echo "DATE=$(date "+%m/%d/%Y")" >> $GITHUB_ENV

      - name: Generate new discussion
        env:
          REPO_ID: 'MDEwOlJlcG9zaXRvcnkxNzg0NTAzOTQ='
          CATEGORY_ID: '"DIC_kwDOCqLv2s4B_m67'
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BODY: |-
            Hello!

            👀 Top-of-Mind: etc.
        run: |-
          gh api graphql \
            -F body="$BODY" \
            -F title="Weekly Snippets $DATE" \
            -F repositoryId="$REPO_ID" \
            -F categoryId="$CATEGORY_ID" \
            -f query='
          mutation CreateDiscussion($body: String!, $title: String!, $repositoryId: String!, $categoryId: String!) { 
            # input type: CreateDiscussionInput
            createDiscussion(input: {repositoryId: $repositoryId, categoryId: $categoryId, body: $body, title: $title}) {

              # response type: CreateDiscussionPayload
              discussion {
                id
              }
            }
          }'
