
on:
  workflow_dispatch

name: Test Issue Bot

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:

    - uses: imjohnbo/issue-bot@v3
      with:
        title: yo
        body: hi
