name: Repository Dispatch

# Controls when the workflow will run
on:
  repository_dispatch:

jobs:
  # This workflow contains a single job called "echo"
  echo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - run: |-
          echo "heyyyyy!"
